First dose of Chemo

diff --git a/bin/hubot b/bin/hubot
--- a/bin/hubot
+++ b/bin/hubot
@@ -1,105 +1,97 @@
-#!/usr/bin/env coffee
-##
-# hubot [options]
-#
-# Launch an interactive hubot
-#
+#!/bin/bash
 
-Hubot      = require '..'
-Fs         = require 'fs'
-Path       = require 'path'
-HTTP       = require 'http'
-Creator    = require '../src/creator'
-OptParse   = require 'optparse'
+MY_DIR="$( cd "$( dirname $0 )" && pwd)"
 
-Switches = [
-  [ "-h", "--help",            "Display the help information" ],
-  [ "-a", "--adapter ADAPTER", "The Adapter to use" ],
-  [ "-c", "--create PATH",     "Create a deployable hubot" ],
-  [ "-s", "--enable-slash",    "Enable replacing the robot's name with '/' (deprecated)" ],
-  [ "-l", "--alias ALIAS",     "Enable replacing the robot's name with alias" ],
-  [ "-n", "--name NAME",       "The name of the robot in chat" ],
-  [ "-v", "--version",         "Displays the version of hubot installed" ]
-]
+if [ -z "$HUBOT_PLUGINS_DIR" ]
+then
+  HUBOT_PLUGINS_DIR=$MY_DIR/plugins
+fi
 
-Options =
-  path: "."
-  name: "Hubot"
-  create: false
-  adapter: "shell"
-  alias: false
+if [ -z "$HUBOT_ADAPTERS_DIR" ]
+then
+  HUBOT_ADAPTERS_DIR=$MY_DIR/adapters
+fi
 
-Parser = new OptParse.OptionParser(Switches)
-Parser.banner = "Usage hubot [options]"
 
-Parser.on "adapter", (opt, value) ->
-  Options.adapter = value
+usage() {
+cat <<EOF
+usage: $0 options
 
-Parser.on "name", (opt, value) ->
-  Options.name = value
+OPTIONS:
+  -h   Show this message
+  -l   List adapters
+  -p   List plugins
+  -a   Adapter to use (default: shell)
 
-Parser.on "create", (opt, value) ->
-  Options.path = value
-  Options.create = true
+EOF
+}
 
-Parser.on "enable-slash", (opt) ->
-  console.log "WARNING: -s and --enable-slash are deprecated please use -l or --alias '/'"
-  Options.alias = '/'
+PLUGINS=""
+ADAPTERS=""
+ADAPTER="$HUBOT_ADAPTERS_DIR/shell"
 
-Parser.on "alias", (opt, value) ->
-  Options.alias = value
+# This is the only Hubot function available to the adapters
+# It is up to the adapters how to execute the plugins
+# (i.e. in serial or parallel) and what do do with the output.
+list_plugins() {
+    PLUGINS=`find $HUBOT_PLUGINS_DIR -maxdepth 1 -type f -executable`
+}
 
-Parser.on "help", (opt, value) ->
-  console.log Parser.toString()
-  process.exit 0
+export -f list_plugins
+#export $PLUGINS
 
-Parser.on "version", (opt, value) ->
-  Options.version = true
+list_adapters() {
+    ADAPTERS=`find $HUBOT_ADAPTERS_DIR -maxdepth 1 -type f -executable`
+}
 
-Parser.parse process.argv
 
-unless process.platform is "win32"
-  process.on 'SIGTERM', ->
-    process.exit 0
+_print_paths() {
+    # Pretty-print adapter & plugin paths for the command line
+    for p in $@
+    do
+        echo "  `basename $p`"
+    done
+}
 
-if Options.create
-  creator = new Creator.Creator(Options.path)
-  creator.run()
+while getopts "hlpa:" OPTION
+do
+  case $OPTION in
+      h)
+          usage
+          exit 0
+          ;;
+      l)
+          list_adapters
+          echo "Available adapters"
+          _print_paths $ADAPTERS
+          exit 0
+          ;;
+      p)
+          list_plugins
+          echo "Available plugins"
+          _print_paths $PLUGINS
+          exit 0
+          ;;
+      a)
+          ADAPTER="$HUBOT_ADAPTERS_DIR/$OPTARG"
+          ;;
+      ?)
+          usage
+          exit 0
+          ;;
+  esac
+done
 
-else if Options.version
-  package_path = __dirname + "/../package.json"
+if [ ! -e "$ADAPTER" ]
+then
+    echo "Could not find adapter: $ADAPTER"
+    exit 1
+fi
 
-  Fs.readFile package_path, (err,data) ->
-    if err
-      console.error "Could not open package file : %s", err
-      process.exit 1
+if [ ! -x "$ADAPTER" ]
+then
+    echo "Adapter $ADAPTER is not executable"
+    exit 1
+fi
 
-    content = JSON.parse(data.toString('ascii'))
-    console.log content['version']
-
-    process.exit 0
-
-else
-  adapterPath = Path.resolve __dirname, "..", "src", "adapters"
-  robot = Hubot.loadBot adapterPath, Options.adapter, Options.name
-  robot.enableSlash = Options.enableSlash
-  robot.alias = Options.alias
-
-  scriptsPath = Path.resolve ".", "scripts"
-  robot.load scriptsPath
-
-  scriptsPath = Path.resolve "src", "scripts"
-  robot.load scriptsPath
-
-  scriptsFile = Path.resolve "hubot-scripts.json"
-  Path.exists scriptsFile, (exists) =>
-    if exists
-      Fs.readFile scriptsFile, (err, data) ->
-        scripts = JSON.parse data
-        scriptsPath = Path.resolve "node_modules", "hubot-scripts", "src", "scripts"
-        robot.loadHubotScripts scriptsPath, scripts
-
-  robot.run()
-
-# vim:ft=coffee ts=2 sw=2 et :
-
+$ADAPTER
