persist fifo connections to prevent hubot exit on plugin exit
The strategy is to start a process that holds onto the fifo.  In
that case the fifo will not break even when a plugin fails.

diff --git a/bin/hubot b/bin/hubot
--- a/bin/hubot
+++ b/bin/hubot
@@ -119,12 +119,28 @@ inbox_dir="var/hubot/inbox"
 rm "$inbox_dir"/*
 mkdir -p "$inbox_dir"
 
+# Launch a hang process to hold open the fifos and thereby prevent a broken
+# pipe if one of the plugins exits prematurely.  Set a trap to cleanup the
+# hang loop on exit.
+hangpids=" "
+trap '
+status=$?
+for id in ${hangpids}
+do kill -9 "${id}"
+done
+exit $status
+' INT TERM EXIT
+
 for plugin in $PLUGINS
 do
   inbox="$inbox_dir/$(basename "$plugin")"
+
   if ! [ -e "$inbox" ]
   then mkfifo "$inbox"
   fi
+
+  while true; do sleep 1; done < "$inbox" > "$inbox" & 
+  hangpids="${hangpids}$! "
 done
 
 #
@@ -134,7 +150,10 @@ done
 for plugin in $PLUGINS
 do
   inbox="$inbox_dir/$(basename "$plugin")"
-  $plugin < "$inbox" | $SAY &
+  (
+    trap "ln -fs /dev/null '$inbox'; exit"  INT TERM EXIT
+    $plugin < "$inbox" | $SAY
+  ) &
 done
 
 $LISTEN | tee "$inbox_dir"/* >/dev/null
